Added Concrete5 files and deploy hook

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -3,3 +3,33 @@
 # build hook has been run but before the application has been started back
 # up again.  This script gets executed directly, so it could be python, php,
 # ruby, etc.
+
+set -e
+
+if [ -z "$OPENSHIFT_DB_HOST" ]
+then
+echo 1>&2
+    echo "Could not find mysql database. Please run:" 1>&2
+    echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
+    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+    echo 1>&2
+fi
+
+if [! -a "$OPENSHIFT_DATA_DIR/config/site.php" ]
+then
+    mkdir "$OPENSHIFT_DATA_DIR/config"
+    mkdir -p "$OPENSHIFT_DATA_DIR/files/thumbnails"
+    mkdir -p "$OPENSHIFT_DATA_DIR/files/avatars"
+    mkdir -p "$OPENSHIFT_DATA_DIR/files/incoming"
+    mkdir -p "$OPENSHIFT_DATA_DIR/files/tmp"
+    mkdir -p "$OPENSHIFT_DATA_DIR/files/trash"
+    mkdir "$OPENSHIFT_DATA_DIR/packages"
+
+    chmod ugo+rwX "$OPENSHIFT_DATA_DIR/config"
+    chmod ugo+rwX "$OPENSHIFT_DATA_DIR/files"
+    chmod ugo+rwX "$OPENSHIFT_DATA_DIR/packages"
+fi
+
+ln -s "$OPENSHIFT_DATA_DIR/config" "OPENSHIFT_GEAR_DIR/php/config"
+ln -s "$OPENSHIFT_DATA_DIR/files" "OPENSHIFT_GEAR_DIR/php/files"
+ln -s "$OPENSHIFT_DATA_DIR/packages" "OPENSHIFT_GEAR_DIR/php/packages"
